### ISSUE TITLE
Drop dependency on VLD (and use OpCache to dump bytecode instead)

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/foal#1]

**Comment by krakjoe** [comment]
This is just an idea, but pcov could give you the control flow graph for any function/file ... It could either give you the entire thing, or maybe allow you to filter blocks (in the case of this application ~ZEND_BB_REACHABLE) ... any interest in that ?

**Comment by sebastianbergmann** [comment]
Sure. But the main point here is to not depend on something outside of the standard distribution.

**Comment by krakjoe** [comment]
I sort of see where you're coming from, and I hear this said all the time: It confuses me somewhat, nobody cares about relying on memcached, mongodb, redis, apcu, and a bunch of other extensions besides, but when you suggest a userland thing relying on an extension it makes everyone retreat. Leaving windows aside, where installation is a case of downloading a single file, I would say for most users, it doesn't really matter what is part of a standard distribution anyway, because there is no such thing prepared by the group. Almost everyone relies on the packaging decisions made by the maintainer of the packages for their operating system, so what is standard isn't really down to the group anyway. You could bundle extension X with php-src, but it may still require additional installation steps in the real world. Similarly, it makes no difference to most people that all of those extensions I listed are not part of php-src, because package maintainers make them as available as the php runtime itself.

I'm not really trying to talk you round, and as maybe obvious, I'm not really sure of the justification for taking the position that it's bad to rely on extensions, just trying to provide my perspective, and likely the perspective of most extension authors.

Maybe there is something I don't see that does make it bad, and I'd be happy to hear reasoning :)

**Comment by staabm** [comment]
From a userland perspective I can say
- its easy to use what you get from your distribution/hoster (like you said)
- it requires additional effort to use something not part of the distribution/hoster and a lot of people I met are not able to install other extensions or keep them up2date after installed once. Its a real problem of the eco system and would benefit if the process would get easier.
- having less dependencies is always a net win, no matter how easy it would be to resolve them

I totally agree that this situation is not great and its as bad for the userland developer as it is for you as a extension author
